apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        sunpengRvi/demo-jx3-golang-http: true
        sunpengRvi/demo-jx3-golang-http-2: true
        sunpengRvi/jx-onprem: true
        sunpengRvi/jxtest-golang-http: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        sunpengRvi/demo-jx3-golang-http: merge
        sunpengRvi/demo-jx3-golang-http-2: merge
        sunpengRvi/jx-onprem: merge
        sunpengRvi/jxtest-golang-http: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - sunpengRvi/jx-onprem
        - sunpengRvi/demo-jx3-golang-http-2
        - sunpengRvi/demo-jx3-golang-http
        - sunpengRvi/jxtest-golang-http
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - sunpengRvi/jx-onprem
        - sunpengRvi/demo-jx3-golang-http-2
        - sunpengRvi/demo-jx3-golang-http
        - sunpengRvi/jxtest-golang-http
      target_url: http://lighthouse-jx.cn1.wrstudio.cloud/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
