apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: sunpengRvi
    provider: https://github.com
    providerKind: github
    repositories:
    - name: demo-jx3-golang-http
    - name: demo-jx3-golang-http-2
    - name: jxtest-golang-http
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
