filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: tekton-pipelines
repositories:
- name: cdf
  url: https://sunpengrvi.github.io/tekton-helm-chart-stagingcn/
releases:
- chart: cdf/tekton-pipeline
  version: 1.0.2
  name: tekton-pipeline
  values:
  - ../../versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}


